services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8088"
    depends_on:
      - postgresql

  postgresql:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chat_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres-data: {}